https://pandas.pydata.org/docs/user_guide/index.html#user-guide

# Import Pandas

In [42]:
import pandas as pd

## Reading local csv file

In [38]:
df = pd.read_csv("crypto50_combined.csv")
df
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115072 entries, 0 to 115071
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Symbol     115072 non-null  object
 1   Date       115072 non-null  object
 2   Open       115072 non-null  float64
 3   High       115072 non-null  float64
 4   Low        115072 non-null  float64
 5   Close      115072 non-null  float64
 6   Adj Close  115072 non-null  float64
 7   Volume     115072 non-null  int64
dtypes: float64(5), int64(1), object(2)
memory usage: 7.0+ MB
None

## CSV file from URL

In [12]:
import requests 
from io import StringIO

url = "https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url , headers=headers) # all data from usrl stores in here

df2 = pd.read_csv(StringIO(req.text))
print(df2)

                    John       Doe                 120 jefferson st.  \
0                   Jack  McGinnis                      220 hobo Av.
1          John "Da Man"    Repici                 120 Jefferson St.
2                Stephen     Tyler  7452 Terrace "At the Plaza" road
3                    NaN  Blankman                               NaN
4  Joan "the bone", Anne       Jet               9th, at Terrace plc

     Riverside   NJ   08075
0        Phila   PA    9119
1    Riverside   NJ    8075
2     SomeTown   SD   91234
3     SomeTown   SD     298
4  Desert City   CO     123

## Sep Parameter

In [18]:
# by default sep value for .csv is comma ,
# for tdv files use , sep = '\t'
pd.read_csv("file.tsv" , sep = '\t')

          0    50  5  881250949
0         0   172  5  881250949
1         0   133  1  881250949
2       196   242  3  881250949
3       186   302  3  891717742
4        22   377  1  878887116
...     ...   ... ..        ...
99997   880   476  3  880175444
99998   716   204  5  879795543
99999   276  1090  1  874795795
100000   13   225  2  882399156
100001   12   203  3  879959583

[100002 rows x 4 columns]

## Index_col parameter

In [5]:
pd.read_csv("pokemon.csv" , index_col = '#')

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## Header Parameter

In [11]:
pd.read_csv("pokemon.csv" , index_col = '#' ,header = 0)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## usecols parameter

In [18]:
pd.read_csv("crypto50_combined.csv" , usecols = ['Symbol' , 'Date' , 'Open' , 'High'])

       Symbol        Date        Open        High
0         BTC  2014-09-17  465.864014  468.174011
1         BTC  2014-09-18  456.859985  456.859985
2         BTC  2014-09-19  424.102997  427.834991
3         BTC  2014-09-20  394.673004  423.295990
4         BTC  2014-09-21  408.084991  412.425995
...       ...         ...         ...         ...
115067    FET  2026-02-12    0.153988    0.162434
115068    FET  2026-02-13    0.158988    0.168220
115069    FET  2026-02-14    0.164977    0.184459
115070    FET  2026-02-15    0.180971    0.181506
115071    FET  2026-02-16    0.173530    0.175364

[115072 rows x 4 columns]

## squeeze fn : if we need to use a single column : df converted to series

In [28]:
pd.read_csv("crypto50_combined.csv" , usecols = ['Symbol']).squeeze()

0         BTC
1         BTC
2         BTC
3         BTC
4         BTC
         ...
115067    FET
115068    FET
115069    FET
115070    FET
115071    FET
Name: Symbol, Length: 115072, dtype: object

In [29]:
## skiprows/nrows

In [32]:
pd.read_csv('crypto50_combined.csv', skiprows = [0,3] )

,BTC,2014-09-17,465.864013671875,468.17401123046875,452.4219970703125,457.3340148925781,457.3340148925781.1,21056800
0,BTC,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
1,BTC,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
2,BTC,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100
3,BTC,2014-09-22,399.100006,406.915985,397.130005,402.152008,402.152008,24127600
4,BTC,2014-09-23,402.092010,441.557007,396.196991,435.790985,435.790985,45099500
...,...,...,...,...,...,...,...,...
115065,FET,2026-02-12,0.153988,0.162434,0.153906,0.158988,0.158988,40210325
115066,FET,2026-02-13,0.158988,0.168220,0.155946,0.164977,0.164977,37787430
115067,FET,2026-02-14,0.164977,0.184459,0.164954,0.180971,0.180971,54489685
115068,FET,2026-02-15,0.180971,0.181506,0.168727,0.173530,0.173530,54244063
115069,FET,2026-02-16,0.173530,0.175364,0.169666,0.173085,0.173085,40430792

In [34]:
pd.read_csv('crypto50_combined.csv', nrows = 100) # this will import only n rows from the complete data set : Low RAM devices

,Symbol,Date,Open,High,Low,Close,Adj Close,Volume
0,BTC,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
1,BTC,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2,BTC,2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
3,BTC,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
4,BTC,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100
...,...,...,...,...,...,...,...,...
95,BTC,2014-12-21,329.542999,329.628998,318.903015,320.842987,320.842987,15207600
96,BTC,2014-12-22,321.067993,334.117004,320.424988,331.885986,331.885986,22315100
97,BTC,2014-12-23,332.016998,336.286987,329.601990,334.571991,334.571991,16574200
98,BTC,2014-12-24,334.385010,334.740997,321.356995,322.533997,322.533997,15092300
99,BTC,2014-12-25,322.286011,322.670013,316.958008,319.007996,319.007996,9883640

## Encoding Parameter : error -> UnicodeDecodeError => encoding different than UFT8

In [35]:
# pd.read_csv('abc.csv' , encoding = 'latin-1')

## Skip bad lines : missing/extra values

In [37]:
# pd.read_csv("abc.csv" , error_bad_lines = False) # skips all the bad lines

In [ ]:
## dtypes parameter : to over-write data types of entire columns :: dtype = {col_name : data_type}

In [39]:
pd.read_csv('data.csv' , dtype = {"Price" : float})

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

## Handling dates : dates are passed as string (or obj) and hence date fns can not be used on such cols

In [41]:
pd.read_csv("IPL Matches 22 .csv" , parse_dates = ['date'])

AttributeError: module 'pandas' has no attribute 'read'

## Converters

In [45]:
def rename(name):
    if name == "Royal Challengers Banglore":
        return 'RCB'
    else:
        return name

In [48]:
rename("Royal Challengers Banglore")

'RCB'

In [49]:
pd.read_csv("IPL Matches 22 .csv" , converters = {'team1' : rename})

FileNotFoundError: [Errno 2] No such file or directory: 'IPL Matches 22 .csv'

## na_values : letting the compuler know the values to be treated like na (not available) values e.g. : - hyphen

In [53]:
pd.read_csv("pokemon.csv" , na_values= 'Poison')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,NaN,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,NaN,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,NaN,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,NaN,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## Loading a huge data set in chhunks

In [55]:
dfs = pd.read_csv('crypto50_combined.csv', chunksize= 5000) # chunksize = no of rows in each chunk

In [66]:
for chunks in dfs:
    print(chunks.shape)